const constants = {
  modulePath: 'modules/voxludos',
  moduleName: 'voxludos',
  moduleLabel: 'Vox Ludos - Text-to-speech-to-text for FVTT',
};
export default constants;

/*
it-IT-BenignoNeural (Male)
it-IT-CalimeroNeural (Male)
it-IT-CataldoNeural (Male)
it-IT-DiegoNeural1 (Male)
it-IT-ElsaNeural (Female)
it-IT-FabiolaNeural (Female)
it-IT-FiammaNeural (Female)
it-IT-GianniNeural (Male)
it-IT-ImeldaNeural (Female)
it-IT-IrmaNeural (Female)
it-IT-IsabellaNeural (Female)
it-IT-LisandroNeural (Male)
it-IT-PalmiraNeural (Female)
it-IT-PierinaNeural (Female)
it-IT-RinaldoNeural (Male)
en-GB-AbbiNeural (Female)
en-GB-AlfieNeural (Male)
en-GB-BellaNeural (Female)
en-GB-ElliotNeural (Male)
en-GB-EthanNeural (Male)
en-GB-HollieNeural (Female)
en-GB-LibbyNeural (Female)
en-GB-MaisieNeural (Female, Child)
en-GB-NoahNeural (Male)
en-GB-OliverNeural (Male)
en-GB-OliviaNeural (Female)
en-GB-RyanNeural (Male)
en-GB-SoniaNeural (Female)
en-GB-ThomasNeural (Male)
en-US-AIGenerate1Neural1 (Male)
en-US-AIGenerate2Neural1 (Female)
en-US-AmberNeural (Female)
en-US-AnaNeural (Female, Child)
en-US-AriaNeural (Female)
en-US-AshleyNeural (Female)
en-US-BrandonNeural (Male)
en-US-ChristopherNeural (Male)
en-US-CoraNeural (Female)
en-US-DavisNeural (Male)
en-US-ElizabethNeural (Female)
en-US-EricNeural (Male)
en-US-GuyNeural (Male)
en-US-JacobNeural (Male)
en-US-JaneNeural (Female)
en-US-JasonNeural (Male)
en-US-JennyMultilingualNeural3 (Female)
en-US-JennyNeural (Female)
en-US-MichelleNeural (Female)
en-US-MonicaNeural (Female)
en-US-NancyNeural (Female)
en-US-RogerNeural (Male)
en-US-SaraNeural (Female)
en-US-SteffanNeural (Male)
en-US-TonyNeural (Male)
*/